# Netlify設定ファイル

[build]
  # 公開ディレクトリ
  publish = "."

[build.environment]
  # Node.jsのバージョン
  NODE_VERSION = "18"

[functions]
  # Netlify Functionsのディレクトリ
  directory = "netlify/functions"

# Functions用のCORSヘッダー
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "POST, OPTIONS"

# セキュリティヘッダー
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"