name: Test and Lint

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Validate JSON files
      run: |
        for file in $(find . -name "*.json" -not -path "./node_modules/*"); do
          echo "Validating $file"
          python -m json.tool "$file" > /dev/null || exit 1
        done
    
    - name: Check file permissions
      run: |
        # 実行可能ファイルがないことを確認
        ! find . -type f -name "*.html" -o -name "*.css" -o -name "*.js" | xargs -I {} test -x {}
    
    - name: Security scan
      run: |
        # 基本的なセキュリティチェック
        echo "Checking for hardcoded credentials..."
        ! grep -r "password\s*=\|api_key\s*=\|secret\s*=" --include="*.js" --include="*.html" . || echo "Warning: Possible hardcoded credentials found"
    
    - name: Check links
      run: |
        # 内部リンクの確認
        echo "Checking internal links..."
        grep -h -o 'href="[^"]*\.html"' *.html | sed 's/href="//;s/"//' | sort -u | while read link; do
          if [ ! -f "$link" ]; then
            echo "Warning: Broken link found: $link"
          fi
        done